project:
  type: website
  output-dir: docs
  
website:
  title: "Introduction to R for Biology & Ecology"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - sidebar:RBasics
      - sidebar:wrangling
      - sidebar:Graphs
      - sidebar:quarto
      - sidebar:b_stats
  
  sidebar:
    - id: RBasics
      title: "R Basics"
      style: "docked"
      background: light
      contents: 
       - getting_started.qmd
       - rbasics.qmd
    
    - id: wrangling
      title: "Tidyverse data wrangling"
      style: "docked"
      background: light
      contents: 
       - intro_tidyverse.qmd
       - pipe.qmd
       - groupsmeans.qmd
       - datetime.qmd
       
      
    - id: Graphs
      title: "Graphs"
      style: "docked"
      background: light
      contents: 
       - basic_graphs.qmd
       - colors.qmd
       - shapes.qmd
       - themes.qmd
       - axes.qmd
       - facets.qmd
       
    - id: quarto
      title: "Using Quarto"
      style: "docked"
      background: light
      contents: 
       - usingquarto.qmd
       
    - id: b_stats
      title: "Beginner Stats"
      style: "docked"
      background: light
      contents: 
       - cor_chi.qmd
       - regression.qmd
       - t_test.qmd
  
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

