project:
  type: website
  output-dir: docs
  
website:
  title: "website_code"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - testpage.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

