project:
  type: website
  output-dir: docs
  
website:
  title: "Introduction to R for Bio/Eco/Evo"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - sidebar:RBasics
      - sidebar:quarto
  
  sidebar:
    - id: RBasics
      title: "R Basics"
      style: "docked"
      background: light
      contents: 
       - getting_started.qmd
       - rbasics.qmd
    
    - id: quarto
      title: "Using Quarto"
      contents: 
       - usingquarto.qmd
  
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

