project:
  type: website
  output-dir: docs
  
website:
  title: "Introduction to R for Bio/Eco/Evo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - getting_started.qmd
      - rbasics.qmd
      - usingquarto.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

